# Extracted from https://github.com/jizt-it/jizt-api-spec/blob/main/.github/workflows/build-docs.yml
name: Build docs
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        run: sh ./docs/make.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
          exclude_assets: ".github,openapi,.redocly.yaml,LICENSE,README.md,make.sh"
